<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ZeroRecover.UI</RootNamespace>
    <AssemblyName>ZeroRecover</AssemblyName>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="app.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroRecover.Core\ZeroRecover.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZeroUI.Wpf" Version="1.5.0" />
    <PackageReference Include="ZeroSystem.Core" Version="1.0.0" />
  </ItemGroup>
</Project>
